CREATE TABLE PERSON (Ssn VARCHAR2(10) CONSTRAINT Ssn_PK PRIMARY KEY,Fname VARCHAR2(30) NOT NULL,Lname VARCHAR2(30) NOT NULL,
Email VARCHAR2(100) CONSTRAINT Email_UQ UNIQUE, Phone VARCHAR2(20) CONSTRAINT Phone_UQ UNIQUE);



CREATE TABLE COLLEGE_OF_CS(CollegeID NUMBER(10) CONSTRAINT CollegeID_PK PRIMARY KEY,Location VARCHAR2(100) NOT NULL, Phone VARCHAR2(20));

CREATE TABLE DEPARTMENT ( DeptID  NUMBER(10) CONSTRAINT Department_PK PRIMARY KEY,Dept_Name  VARCHAR2(100) NOT NULL,
Phone  VARCHAR2(20),Office VARCHAR2(50), CollegeID  NUMBER(10) NOT NULL,
CONSTRAINT CollegeID_FK FOREIGN KEY (CollegeID) REFERENCES COLLEGE_OF_CS(CollegeID));

CREATE TABLE SEMESTER (SemesterID NUMBER(10) CONSTRAINT Semester_PK PRIMARY KEY,
Term  VARCHAR2(20) NOT NULL, Start_Date DATE NOT NULL, End_Date DATE NOT NULL);


CREATE TABLE COURSE ( CourseID  NUMBER(10) CONSTRAINT Course_PK PRIMARY KEY,
Course_Name  VARCHAR2(100) NOT NULL,Credits  NUMBER(2) NOT NULL, DeptID  NUMBER(10) NOT NULL,
CONSTRAINT Course_Dept_FK FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID));


CREATE TABLE STUDENT (Sssn  VARCHAR2(10) CONSTRAINT Sssn_PK PRIMARY KEY, Gendar VARCHAR2(10),
Address VARCHAR2(100), Admission_Year NUMBER(4), DeptID  NUMBER(10) NOT NULL,
CONSTRAINT Sssn_FK FOREIGN KEY (Sssn) REFERENCES PERSON(Ssn),
CONSTRAINT DeptID_FK FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID));

CREATE TABLE MASTER ( Sssn VARCHAR2(10) CONSTRAINT Msssn_PK PRIMARY KEY,Program_Focus VARCHAR2(100),
CONSTRAINT Msssn_FK FOREIGN KEY (Sssn) REFERENCES STUDENT(Sssn));

CREATE TABLE PHD ( Sssn VARCHAR2(10) CONSTRAINT PhD_PK PRIMARY KEY, Research_Area VARCHAR2(100),
CONSTRAINT PhD_FK FOREIGN KEY (Sssn) REFERENCES STUDENT(Sssn));

CREATE TABLE UNDER_GRADUATE ( Sssn VARCHAR2(10) CONSTRAINT USssn_PK PRIMARY KEY,
LevelN NUMBER(2),CONSTRAINT USssn_FK FOREIGN KEY (Sssn) REFERENCES STUDENT(Sssn));

CREATE TABLE INSTRUCTOR (Issn  VARCHAR2(10) CONSTRAINT Issn_PK PRIMARY KEY, Office VARCHAR2(50),
DeptID NUMBER(10) NOT NULL, Rank VARCHAR2(50),
Experience_Years NUMBER(2),Contract_Type VARCHAR2(50),
Promotion_Eligibility VARCHAR2(10),
CONSTRAINT Dept_FK FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID));



CREATE TABLE ENROLLMENT ( EnrollmentID    NUMBER(10) CONSTRAINT EnrollmentID_PK PRIMARY KEY, Status VARCHAR2(20),
Enrollment_Date DATE, Grade_Value VARCHAR2(5), Sssn VARCHAR2(10) NOT NULL,
CourseID NUMBER(10) NOT NULL,SemesterID  NUMBER(10) NOT NULL,CONSTRAINT ESssn_FK FOREIGN KEY (Sssn) REFERENCES STUDENT(Sssn),
CONSTRAINT ECourseID_FK  FOREIGN KEY (CourseID)  REFERENCES COURSE(CourseID),
CONSTRAINT ESemesterID_FK FOREIGN KEY (SemesterID)  REFERENCES SEMESTER(SemesterID));



CREATE TABLE OFFERED_IN (CourseID NUMBER(10)NOT NULL,SemesterID NUMBER(10)NOT NULL,
CONSTRAINT Offered_PK PRIMARY KEY (CourseID, SemesterID),
CONSTRAINT OCourseID_FK FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID),
CONSTRAINT OSemesterID_FK FOREIGN KEY (SemesterID) REFERENCES SEMESTER(SemesterID));

CREATE TABLE TEACHES ( Issn VARCHAR2(10), CourseID NUMBER(10),
CONSTRAINT Teaches_PK PRIMARY KEY (Issn, CourseID),
CONSTRAINT TIssn_FK FOREIGN KEY (Issn) REFERENCES INSTRUCTOR(Issn),
CONSTRAINT Teach_CourseID_FK FOREIGN KEY (CourseID) REFERENCES COURSE(CourseID));
